apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: local-storage
#spec:
#  storageClassName: mylocalstorage
#  capacity:
#    storage: 20Gi
#  accessModes:
#    - ReadWriteMany
#  hostPath:
#    path: "/mnt/some/directory/structure/"
#    type: DirectoryOrCreate
  
